[project]
name = "conference_mapper"
version = "0.1.0"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "geopy>=2.4.1",
    "psycopg2>=2.9.10",
    "pydantic>=2.10.6",
    "scrapy>=2.12.0",
]
