FROM postgres:16-alpine

# Using dummy values for user/password
ENV POSTGRES_DB=conference_mapper
ENV POSTGRES_USER=malevolentelk
ENV POSTGRES_PASSWORD=malevolentelk

# Expose PostgreSQL port
EXPOSE 5432
